/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 
 */
public class JFRPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFRPrincipal
     */
    public JFRPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        JMNLineal = new javax.swing.JMenu();
        JMIJacobi = new javax.swing.JMenuItem();
        JMIGaussSeidel = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMPuntoFijo = new javax.swing.JMenuItem();
        jMNewton = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/fondoMN.jpg"))); // NOI18N

        jMenuBar1.setBackground(new java.awt.Color(0, 51, 255));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));

        jMenu1.setText("Metodo");

        JMNLineal.setText("Ecuaciones lineales");

        JMIJacobi.setText("Jacobi");
        JMIJacobi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIJacobiActionPerformed(evt);
            }
        });
        JMNLineal.add(JMIJacobi);

        JMIGaussSeidel.setText("Gauss Seidel");
        JMIGaussSeidel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIGaussSeidelActionPerformed(evt);
            }
        });
        JMNLineal.add(JMIGaussSeidel);

        jMenu1.add(JMNLineal);

        jMenu3.setText("Ecuaciones No lineales");

        jMPuntoFijo.setText("Punto Fijo");
        jMPuntoFijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMPuntoFijoActionPerformed(evt);
            }
        });
        jMenu3.add(jMPuntoFijo);

        jMNewton.setText("Newton");
        jMNewton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMNewtonActionPerformed(evt);
            }
        });
        jMenu3.add(jMNewton);

        jMenu1.add(jMenu3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMIJacobiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIJacobiActionPerformed
      dlgJacobi vnt = new dlgJacobi(this,true);
        vnt.setVisible(true);  
    }//GEN-LAST:event_JMIJacobiActionPerformed

    private void JMIGaussSeidelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIGaussSeidelActionPerformed
        dlgGaussSeidel vtn = new dlgGaussSeidel(this, true);
        vtn.setVisible(true);
                              
    }//GEN-LAST:event_JMIGaussSeidelActionPerformed

    private void jMPuntoFijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMPuntoFijoActionPerformed
        DlgFijo vtn = new DlgFijo(this, true);
        vtn.setVisible(true);
    }//GEN-LAST:event_jMPuntoFijoActionPerformed

    private void jMNewtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMNewtonActionPerformed
        DlgNewton vtn = new DlgNewton(this, true);
        vtn.setVisible(true);
    }//GEN-LAST:event_jMNewtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFRPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFRPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFRPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFRPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFRPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMIGaussSeidel;
    private javax.swing.JMenuItem JMIJacobi;
    private javax.swing.JMenu JMNLineal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMNewton;
    private javax.swing.JMenuItem jMPuntoFijo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
